### ISSUE TITLE
Animated emoji elements not rendering on safari

### ISSUE THREAD

**Issue by patcon** [JohnPhamous/live-reactions#1]
## Steps to Reproduce
1. Open Safari 15.3 in OSX
2. Open this page: https://live-reactions-one.vercel.app/2
3. Click any emoji

## Expected Behaviour
Would expect the additioanl emoji DIV elements to render below the clicked on, like they do in Chrome, Edge, and Firefox.

## Observed Behaviour
No additional emoji appear. Opening up the inspector shows that the DIV elements appear in the DOM, and are highlighted when moused over, but nothing is rendered.

---

I know this is _totally_ outside the scope of what this is trying to demonstrate, but wondering if you ever resolved this for the Vercel Ship broadcast. Thanks for any advice! Even just confirming that this was a known bug that you didn't resolve, that would help me be at peace with this :)

Hope you're well!

**Comment by JohnPhamous** [comment]
Works on Safari 16.5.2.

This is an intermittent step from the final demo so I won't be putting any time into debugging it.

**Comment by patcon** [comment]
Thanks! I respect that guard on your attention. I was just showing the first demonstrable break, to show that it had nothing to do with the animation.

It definitely doesn't work for https://live-reactions-one.vercel.app/7 either, which you can verify on browserstack for any Safari version < 16

Happy to share if I find a fix, regardless. Might just show a warning for v15 or lower
